# local/default
buda:
  ## TODO: put real values here and work with external application.yml in production (to keep credentials secret)
  S3_ACCESS_KEY_ID: 'xxxdevelopment system valuexxx'
  S3_BUCKET: 'xxxdevelopment system valuexxx'
  S3_ENDPOINT: 'xxxdevelopment system valuexxx'
  S3_MAX_CONNECTIONS: 'xxxdevelopment system valuexxx'
  S3_REGION:  'xxxdevelopment system valuexxx'
  S3_RESOLVER: 'io.bdrc.iiif.resolver.BdrcS3Resolver'
  S3_SECRET_KEY: 'xxxdevelopment system valuexxx'

endpoints:
  hypermedia:
    enabled: true

info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@maven.compiler.source@'
      target: '@maven.compiler.target@'
    project:
      name: '@project.name@'
      groupId: '@project.groupId@'
      artifactId: '@project.artifactId@'
      version: '@project.version@'

management:
  context-path: '/monitoring'
  port: 9001
  security:
    enabled: false

security:
  basic:
    enabled: false
  headers:
    # disables pragma no-cache header
    cache: false

server:
  contextPath: /iiif
  server-header: "@project.name@ v@project.version@"

spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
    mode: HTML

---

# PROD

buda:
  ## TODO: put real values here and work with external application.yml in production (to keep credentials secret)
  S3_ACCESS_KEY_ID: 'xxxproduction system valuexxx'
  S3_BUCKET: 'xxxproduction system valuexxx'
  S3_ENDPOINT: 'xxxproduction system valuexxx'
  S3_MAX_CONNECTIONS: 'xxxproduction system valuexxx'
  S3_REGION:  'xxxproduction system valuexxx'
  S3_RESOLVER: 'io.bdrc.iiif.resolver.BdrcS3Resolver'
  S3_SECRET_KEY: 'xxxproduction system valuexxx'

management:
  security:
    enabled: true

security:
  user:
    name: admin
    password: secret

spring:
  profiles: PROD
  thymeleaf:
    cache: true