# local/default
buda:
  ## TODO: put real values here and work with external application.yml in production (to keep credentials secret)
  S3_ACCESS_KEY_ID: access_key_id
  S3_BUCKET: bucket
  S3_ENDPOINT: endpoint
  S3_MAX_CONNECTIONS: max_connections
  S3_REGION:  region
  S3_RESOLVER: io.bdrc.iiif.resolver.BdrcS3Resolver
  S3_SECRET_KEY: secret_key

endpoints:
  hypermedia:
    enabled: true

info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@maven.compiler.source@'
      target: '@maven.compiler.target@'
    project:
      name: '@project.name@'
      groupId: '@project.groupId@'
      artifactId: '@project.artifactId@'
      version: '@project.version@'

management:
  context-path: '/monitoring'
  port: 9001
  security:
    enabled: false

security:
  basic:
    enabled: false
  headers:
    # disables pragma no-cache header
    cache: false

server:
  contextPath: /iiif
  server-header: "@project.name@ v@project.version@"

spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
    mode: HTML

---

# PROD
management:
  security:
    enabled: true

security:
  user:
    name: admin
    password: secret

spring:
  profiles: PROD
  thymeleaf:
    cache: true